spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/songci?useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1411jtt
mybatis:
      type-aliases-package: com.dxc.songci.model
      mapper-locations: classpath*:/mybatis/mapper/*.xml
